Controllers/CommentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PhotoSharingApplication1.Models;

namespace PhotoSharingApplication.Controllers
{
    public class CommentController : Controller
    {
        private IPhotoSharingContext context;

        //Constructors
        public CommentController()
        {
            context = new PhotoSharingContext();
        }

        public CommentController(IPhotoSharingContext Context)
        {
            context = Context;
        }


        [ChildActionOnly]
        public PartialViewResult _CommentsForPhoto(int PhotoId)
        {
            var comments = from c in context.Comments
                           where c.PhotoID == PhotoId
                           select c;
            ViewBag.PhotoId = PhotoId;
            return PartialView("_CommentsForPhoto", comments.ToList());
        }

        [HttpPost]
        public PartialViewResult _CommentsForPhoto(Comment comment, int PhotoId)
        {
            comment.UserName = "Thanigaivel";
            context.Add<Comment>(comment);
            context.SaveChanges();
            var comments = from c in context.Comments
                           where c.PhotoID == PhotoId
                           select c;
            ViewBag.PhotoId = PhotoId;
            return PartialView("_CommentsForPhoto", comments.ToList());
        }

       
       
         [ChildActionOnly]
        public PartialViewResult _Create(int PhotoId)
        {
            Comment newComment = new Comment();
            newComment.PhotoID = PhotoId;

            ViewBag.PhotoID = PhotoId;
            return PartialView("_CreateAComment");
        }
        //
        // GET: /Comment/Delete/5
        public ActionResult Delete(int id = 0)
        {
            Comment comment = context.FindCommentById(id);
            ViewBag.PhotoID = comment.PhotoID;
            if (comment == null)
            {
                return HttpNotFound();
            }
            return View(comment);
        }

        //
        // POST: /Comment/Delete/5
        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            Comment comment = context.FindCommentById(id);
            context.Delete<Comment>(comment);
            context.SaveChanges();
            return RedirectToAction("Display", "Photo", new { id = comment.PhotoID });
        }

    }
}

Controllers/PhotoController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;
using PhotoSharingApplication1.Models;
using System.Globalization;
using PhotoSharingApplication1.Models;


namespace PhotoSharingApplication1.Controllers
{
    [ValueReporter]
 //   [HandleError(View= "Error")]
    public class PhotoController : Controller
    {
      //  private PhotoSharingContext db = new PhotoSharingContext();
        private IPhotoSharingContext db;

        public PhotoController()
        {
            db = new PhotoSharingContext();
        }

        public PhotoController(IPhotoSharingContext Context)
        {
            db = Context;
        }
        //
        // GET: /Photo/
       // [OutputCache(Duration=600, Location=OutputCacheLocation.Server, VaryByParam="none")]
        public ActionResult Index()
        {
            return View(db.Photos.ToList());
            //return View("Index");
        }


        [ChildActionOnly]
        public ActionResult _PhotoGallery(int number = 0)
        {
            List<Photo> photos;
            if (number == 0)
            {
                photos = db.Photos.ToList();
            }
            else
            {
                photos = (from p in db.Photos
                          orderby p.CreatedDate descending
                          select p).Take(number).ToList();
            }
            return PartialView("_PhotoGallery", photos);
        }

        public ActionResult Display(int id=1)
        {
            Photo photo = db.FindPhotoById(id);
            if(photo == null)
            {
                return HttpNotFound();
            }
            return View("Display", photo);
        }


        public ActionResult DisplayByTitle(string title)
        {
           
            Photo photo = db.FindPhotoById(1);
            if(photo == null)
            {
                return HttpNotFound();
            }
            return View("Display", photo);

        }
        //
        // GET: /Photo/Details/5

        public ActionResult Details(int id = 0)
        {
            Photo photo = db.FindPhotoById(id);
            if (photo == null)
            {
                return HttpNotFound();
            }
            return View(photo);
        }

        //
        // GET: /Photo/Create

        public ActionResult Create()
        {
           // return View();
            Photo newPhoto = new Photo();
            newPhoto.CreatedDate = DateTime.Today;
            return View("Create", newPhoto);
        }

        //
        // POST: /Photo/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Photo photo, HttpPostedFileBase image)
        {
            photo.CreatedDate = DateTime.Today;
            if (ModelState.IsValid)

            {
                if(image != null)
                {
                    photo.ImageMimeType = image.ContentType;
                    photo.PhotoFile = new byte[image.ContentLength];
                    image.InputStream.Read(photo.PhotoFile, 0, image.ContentLength);
                    string stringlonglat = CheckLocaiton("India");
                    if(stringlonglat.StartsWith("Success"))
                    {
                        char[] splitChars = { ':' };
                        string[] coordinates = stringlonglat.Split(splitChars);
                        
                    }

                }
                db.Add<Photo>(photo);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View("Create", photo);
        }

        //
        // GET: /Photo/Edit/5

        public ActionResult Edit(int id = 0)
        {
            Photo photo = db.FindPhotoById(id);
            if (photo == null)
            {
                return HttpNotFound();
            }
            return View(photo);
        }

        //
        // POST: /Photo/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Photo photo)
        {
            if (ModelState.IsValid)
            {
              //  db.Entry(photo).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(photo);
        }

        //
        // GET: /Photo/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Photo photo = db.FindPhotoById(id);
            if (photo == null)
            {
                return HttpNotFound();
            }
            return View(photo);
        }

        //
        // POST: /Photo/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Photo photo = db.FindPhotoById(id);
            db.Delete<Photo>(photo);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        [OutputCache(Duration=600, Location=OutputCacheLocation.Server, VaryByParam="id")]
        public FileContentResult GetImage(int id)
        {
            Photo photo = db.FindPhotoById(id);

            if(photo != null)
            {
                return File(photo.PhotoFile, photo.ImageMimeType);
            }
            else
            {
                return null;
            }
        }

        public ActionResult SlideShow()
        {

          //  throw new NotImplementedException("The Slide show action is not yet ready");
            return View("SlideShow", db.Photos.ToList());
        }


        public ActionResult FavoritesSlideShow()
        {

            List<Photo> favPhotos = new List<Photo>();
            List<int> favoriteIds = Session["Favorites"] as List<int>;
            if(favoriteIds == null)
            {
                favoriteIds = new List<int>();
                Photo currentPhoto;
                foreach(int CurrentId in favoriteIds)
                {
                    currentPhoto = db.FindPhotoById(CurrentId);
                    if(currentPhoto != null)
                    {

                        favPhotos.Add(currentPhoto);
                    }
                }

            }
            return View("SlideShow", favPhotos);
        }

        public ContentResult AddFavourite(int PhotoId)
        {
            List<int> favoriteIds = Session["Favorites"] as List<int>;
            if(favoriteIds == null)
            {
                favoriteIds = new List<int>();
                favoriteIds.Add(PhotoId);
                Session["Favorites"] = favoriteIds;

            }
            return Content("The Picture has been added to your favorites", "text/plain", System.Text.Encoding.Default);
        }

        private string CheckLocaiton(string location)
        {
            PhotoSharingApplication1.net.cloudapp.thanigaivellocationservice.Service1 client = null;
            
            string response = "";
            try
            {
                client = new net.cloudapp.thanigaivellocationservice.Service1();
                response = client.Getlocation("India");

            }catch(Exception e)
            {

                response = "Error: " + e.Message;
            }

            return response;
        }


        //protected override void Dispose(bool disposing)
        //{
        //    db.Dispose();
        //    base.Dispose(disposing);
        //}
    }
}

Views/Shared/_CommentsForPhoto.cshtml
@model IEnumerable<PhotoSharingApplication1.Models.Comment>

<h3>Comment</h3>
@using (Ajax.BeginForm("_CommentsForPhoto", new { PhotoId = ViewBag.PhotoID }, new AjaxOptions { UpdateTargetId = "comments-tool" }))
{
    <div id="comments-tool">
        <div id="all-comments">
            @foreach (var item in Model)
            {
                <div class="photo-comment">


                    <div class="photo-comment-from">
                        From:@Html.DisplayFor(modelItem => item.UserName)
                    </div>



                    <div class="photo-comment-subject">
                        Subject:@Html.DisplayFor(modelItem => item.Subject)
                    </div>



                    <div class="photo-comment-body">
                        Body: @Html.DisplayFor(modelItem => item.Body)
                    </div>

                    @Html.ActionLink("Delete this comment", "Delete", new { id = item.CommentID })
                </div>
            }
        </div>

        <div id="add-comment" class="add-comment-box">
            @Html.Action("_Create", "Comment", new { PhotoId = ViewBag.PhotoId })
        </div>
    </div>

}

Views/Shared/_CreateAComment.cshtml
@model PhotoSharingApplication1.Models.Comment

@Html.ValidationSummary(true)

<div class="add-comment-tool">
    <div>
        <span class="editor-label">
            Subject:
        </span>
        <span class="editor-field">
            @Html.EditorFor(model => model.Subject)
        </span>
    </div>

    <div>
        <span class="editor-label">
            Body:
        </span>
        <span class="editor-field">
            @Html.EditorFor(model => model.Body)
        </span>

    </div>
</div>
<input type="submit" value="Create" />

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>@ViewBag.Title - My ASP.NET MVC Application</title>
        <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
        <meta name="viewport" content="width=device-width" />
        @Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")
    </head>
    <body>
        <header>
            <div class="content-wrapper">
                <div class="float-left">
                    <p class="site-title">@Html.ActionLink("your logo here", "Index", "Home")</p>
                </div>
                <div class="float-right">
                    <section id="login">
                        @Html.Partial("_LoginPartial")
                    </section>
                    <nav>
                        <ul id="menu">
                            <li>@Html.ActionLink("Home", "Index", "Home")</li>
                            <li>@Html.ActionLink("About", "About", "Home")</li>
                            <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                        </ul>
                    </nav>
                </div>
            </div>
        </header>
        <div id="body">
            @RenderSection("featured", required: false)
            <section class="content-wrapper main-content clear-fix">
                @RenderBody()
            </section>
        </div>
        <footer>
            <div class="content-wrapper">
                <div class="float-left">
                    <p>&copy; @DateTime.Now.Year - My ASP.NET MVC Application</p>
                </div>
            </div>
        </footer>

        @Scripts.Render("~/bundles/jquery")
        @RenderSection("scripts", required: false)
    </body>
</html>

Views/Shared/_MainLayout.Mobile.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link type="text/css" rel="stylesheet" href="~/Content/PhotoSharingStyles.css"/>
    <script src="http://ajax.aspnetcdn.com/ajax/jquery/jquery-1.8.0min.js" type="text/javascript"></script>
    <script src="http://ajax.aspnetcdn.com/ajax/mvc/3.0/jquery.unobtrusive-ajax.js" type="text/javascript"></script>
</head>
<body>
    <div>
         <h1 class="site-page-title">Adventure Works <br/> Photo Sharing</h1>
		<h2>Mobile Site</h2>
        <div class = "clear-floats" />
        <div id="topmenu">
            @Html.MvcSiteMap().Menu(false, true, true)
            
        </div>
        <div id="breadcrumb">
          @Html.MvcSiteMap().SiteMapPath()
        </div>
        <div>@RenderBody()</div>
    </div>
</body>
</html>

Views/Shared/_MainLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link type="text/css" rel="stylesheet" href="~/Content/PhotoSharingStyles.css"/>
    <link type="text/css" rel="stylesheet" href="http://code.jquery.com/ui/1.9.2/themes/base/jquery-ui.css"/>
    <script src="http://ajax.aspnetcdn.com/ajax/jquery/jquery-1.8.0.min.js" type="text/javascript"></script>
    <script src="http://ajax.aspnetcdn.com/ajax/mvc/3.0/jquery.unobtrusive-ajax.js" type="text/javascript"></script>
    <script src="http://ajax.aspnetcdn.com/ajax/jquery.ui/1.10.0/jquery-ui.min.js" type="text/javascript">

    </script>
</head>
<body>
    <div>
         <h1 class="site-page-title" >Thanigaivel Photo Sharing Application</h1>
        <div class="clear-floats" />
        <div id="topmenu">
            @Html.MvcSiteMap().Menu(false, true, true)
        </div>
        <div id="breadcrumb">
          Current Location: @Html.MvcSiteMap().SiteMapPath()
            @if(Session["Favorites"] != null)
            {
                <div id="favorites-link">
                    @Html.ActionLink("Favorite Photos", "FavoriteSlideShow", "Photo")
                </div>
            }
        </div>
        <div>@RenderBody()</div>
    </div>
</body>
</html>